---
apiVersion: batch/v1
kind: Job
metadata:
  name: gitlab-error-processing-job
  namespace: custom
spec:
  ttlSecondsAfterFinished: 7200
  template:
    spec:
      containers:
      - name: gitlab-error-processing-job
        image: ghcr.io/mvandenburgh/upload-gitlab-failure-logs:0.0.1
        imagePullPolicy: Always
        env:
        - name: GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitlab-error-processor
              key: gitlab-token
        - name: OPENSEARCH_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: gitlab-error-processor
              key: opensearch-endpoint
        - name: OPENSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: gitlab-error-processor
              key: opensearch-username
        - name: OPENSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-error-processor
              key: opensearch-password
      nodeSelector:
        spack.io/node-pool: base
