name: Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker-image: opensearch-index-build-logs
            image-version: 0.0.3
          - docker-image: pipeline-dashboard-webservice
            image-version: 0.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.docker-image }}
        id: docker-build-push
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.docker-image }}
          file: ./${{ matrix.docker-image }}/Dockerfile
          push: true
          tags: ghcr.io/mvandenburgh/${{ matrix.docker-image }}:${{ matrix.image-version }}
